/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_gui;

import DbModel.AccountModel;
import DbModel.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mughees
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    int xMouse;
     int YMouse;

     
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login1 = new javax.swing.JButton();
        pass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createAccount1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(788, 1254));
        jPanel1.setLayout(null);

        Login1.setBackground(new java.awt.Color(255, 255, 255));
        Login1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Login1.setForeground(new java.awt.Color(255, 255, 255));
        Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/Login.bbb.jpg"))); // NOI18N
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        jPanel1.add(Login1);
        Login1.setBounds(110, 230, 100, 80);

        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(pass);
        pass.setBounds(200, 150, 280, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/Login.pass.jpg"))); // NOI18N
        jLabel3.setText("Account Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 150, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/Login.title.jpg"))); // NOI18N
        jLabel1.setText("LOGin");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 10, 210, 70);

        username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(username);
        username.setBounds(200, 90, 280, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/Login.user.jpg"))); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 150, 30);

        createAccount1.setBackground(new java.awt.Color(51, 51, 51));
        createAccount1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createAccount1.setForeground(new java.awt.Color(255, 255, 255));
        createAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/Login.bsad.jpg"))); // NOI18N
        createAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccount1ActionPerformed(evt);
            }
        });
        jPanel1.add(createAccount1);
        createAccount1.setBounds(400, 240, 90, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/11873908_845220685574220_1650186313_n.jpg"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -10, 120, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/cross.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 10, 20, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/min.PNG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(550, 10, 20, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_gui/Login.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 350);
        jPanel1.add(jSlider1);
        jSlider1.setBounds(440, 70, 200, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
       
          AccountModel acm = new AccountModel();
          User n=null;
        try {
            n = acm.findAccount(username.getText());
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(this , "Invalid Input.Try Again");
        }
          if(n!=null)
          {
              
              MainPanel mp=null;
              try {
                  mp = new MainPanel();
              } catch (SQLException ex) {
                
              }
              try {
                  mp.setUserId(n.id);
              } catch (SQLException ex) {
                  
              }
              mp.setVisible(true);
              this.dispose();
          }
          else
          {
              JOptionPane.showMessageDialog(this, "Invalid Input.Try Again");
          }
       
        
    }//GEN-LAST:event_Login1ActionPerformed

    private void createAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccount1ActionPerformed
       

        AccountModel acm = new AccountModel();
        try 
        {
            acm.insertAccount(pass.getText(), username.getText());
          
          User n=null;
      
            n = acm.findAccount(pass.getText());
     
              MainPanel mp=new MainPanel();
              mp.setUserId(n.id);
              
              this.dispose();
            
        } catch (SQLException ex) 
        {
            
        }
        
        
    }//GEN-LAST:event_createAccount1ActionPerformed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - YMouse);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
       
         xMouse = evt.getX();
        YMouse = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       
         this.setExtendedState(this.getExtendedState() | this.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login1;
    private javax.swing.JButton createAccount1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
